name = "example-project"
type = "javascript"
account_id = "8be772befd147a8df540aae0fa15c047"

[build]
command = "npm install && npm run build"
[build.upload]
format = "service-worker"

[env.staging]
zone_id = "eff05b39c27d06d4f546481661c8ab8f"
workers_dev = true